before_build:
  - nuget restore

build_script:
  - msbuild libplist.vcxproj /p:Configuration=Debug /p:Platform=Win32 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild libplist.vcxproj /p:Configuration=Debug /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild libplist.vcxproj /p:Configuration=Release /p:Platform=Win32 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild libplist.vcxproj /p:Configuration=Release /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

platform:
  - Win32

configuration:
  - Debug

on_success:
  - cmd: choco install coapp
  - ps: .\CreateNuGetPackage.ps1 -Build $ENV:APPVEYOR_BUILD_NUMBER
  - cmd: appveyor PushArtifact libplist.1.12.%APPVEYOR_BUILD_NUMBER%.nupkg
  - cmd: appveyor PushArtifact libplist.symbols.1.12.%APPVEYOR_BUILD_NUMBER%.nupkg

nuget:
  project_feed: true
  account_feed: true
